config/routes.rb
Rails.application.routes.draw do

  #resources :homes
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  devise_for :users

  #booksにいいねとコメントを結びつける
  resources :books, only: [:show, :create, :edit, :update, :index, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :update, :edit]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  #いいね、コメント
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  #いいね用
  has_many :favorites, dependent: :destroy
  #コメント用
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  validates :email, presence: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

    def after_sign_in_path_for(resource)
      flash[:notice] = "Signed in successfully."
      user_path(current_user.id)
    end

    def after_sign_out_path_for(resource)
      flash[:notice] = "Signed out successfully."
      root_path
    end

    def after_sign_up_path_for(resource)
      flash[:notice] = "Welcome! You have signed up successfully."
      user_path(current_user.id)
    end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :password, :password_confirmation])
    end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def index
    @user = User.find(current_user.id)
    #newはワンちゃんいらない=>createで定義すればよい？
    @book = Book.new
    @books = Book.all
    #@book_comment = Book.new
  end

  #使わない
  def new
    @book = Book.new
  end


  def create
    #データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    #データをDBに保存するためのsaveメソッド実行
    if @book.save
      #フラッシュメッセージ送信
      flash[:notice] = "You have created book successfully."
      #booksの詳細画面へリダイレクトしたい
      redirect_to book_path(@book.id)
    else
      flash[:notice] = "can't be blank"
      redirect_to books_path
    end
  end



  def show
    @book_detail = Book.find(params[:id])
    @user = User.find(@book_detail.user_id)
    @book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    #データを１件取得
    @book = Book.find(params[:id])
    #アップデートする
    if @book.update(book_params)
      #フラッシュメッセージ送信
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      flash[:notice] = "error"
      render :edit
    end
  end

  def destroy
    #データを１件取得
    book = Book.find(params[:id])
    #データを削除
    book.destroy
    redirect_to books_path
  end

  # 投稿データのストロングパラメータ
  private

    def is_matching_login_user
      book = Book.find(params[:id])
      unless book.user_id == current_user.id
        redirect_to books_path
      end
    end


  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]


  def index
    @currentUser = User.find(current_user.id)
    @newBook = Book.new
    @users = User.all
  end

  #userの詳細
  def show
    @user = User.find(params[:id])
    @userBooks = Book.where(user_id: params[:id])
    @new_book = Book.new
  end

  #Userの編集
  def edit
    @user = User.find(params[:id])
  end

  #Userの変更更新
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      flash[:notice] = "is too short (minimum is 2 characters)"
      render :edit
    end
  end

  private

    def is_matching_login_user
      user = User.find(params[:id])
      unless user.id == current_user.id
        redirect_to user_path(current_user.id)
      end
    end

    def set_user
      @user = User.find([:id])
    end

    def user_params
      params.require(:user).permit(:name,:introduction, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
      <h2>Editing Book</h2>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label class="form-label">Title</label>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="form-group">
        <label class="form-label">Opinion</label>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class="actions">
        <%= f.submit 'Update Book', class: "btn btn-success md-3" %>
      </div>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<!-- フラッシュメッセージ -->
<div class="notice">
  <%= flash[:notice] %>
</div>

<div class="container px5 px-sm-0 mt-3">
  <div class="row">
    <div class="col-md-3">
      <!-- template -->
      <%= render partial: "templates/template", locals: { user: @user ,book: @book} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <!-- Booksテーブル -->
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(80, 80) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>
              <!-- いいね -->
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <span class="fa-solid fa-heart"></span><%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <span class="fa-regular fa-heart"></span><%= book.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <td>
              <!--コメント-->
              コメント数:<%= book.book_comments.count %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<!-- フラッシュメッセージ -->
<div class="notice">
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "templates/template", locals: { user: @user ,book: @book} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td style="display: flex; flex-direction: colum;">
              <!--User プロフィール画像-->
              <%= link_to user_path(@book_detail.user.id) do %>
                <%= image_tag @book_detail.user.profile_image, size: "80x80" %>
                <%= @book_detail.user.name %>
              <% end %>
            </td>
            <!--titleを本の詳細画面にする -->
            <td><%= link_to @book_detail.title, book_path(@book_detail.id) %></td>
            <td><%= @book_detail.body%></td>
            <!-- いいね -->
            <td>
              <% if @book_detail.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book_detail), method: :delete do %>
                  <span class="fa-solid fa-heart"></span><%= @book_detail.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book_detail), method: :post do %>
                  <span class="fa-regular fa-heart"></span><%= @book_detail.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <!--コメント-->
            <td>コメント数:<%= @book_detail.book_comments.count %></td>

            <% if @book_detail.user_id  == current_user.id %>
              <td>
                <%= link_to "Edit", edit_book_path(@book_detail.id), class:"btn btn-success" %>
              </td>
            <% end %>
            <!--削除-->
            <% if @book_detail.user_id  == current_user.id %>
              <td>
                <%= link_to "Destroy", book_path(@book_detail.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <!--投稿に対するコメント一覧, コメント数-->
      <% @book_detail.book_comments.each do |book_comment| %>

        <table class="table">
          <tbody>
            <td><%= image_tag book_comment.user.get_profile_image(80,80) %></td>
            <td><%= link_to book_comment.user.name, user_path(book_comment.user.id) %></td>
            <td><%= content_tag :div, book_comment.comment %></td>
            <td>
              <% if current_user.id == book_comment.user_id %>
                <div class="col-md-2">
                  <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn btn-danger" %>
                </div>
              <% end %>
            </td>
          </tbody>
        </table>
      <% end %>
      <!-- コメント入力フォーム -->
      <div class="row">
        <div class="col-12">
          <div class="form-group">
            <%= form_with model: [@book_detail, @book_comment], url: book_book_comments_path(@book_detail) do |f| %>
              <%= f.text_area :comment, rows: '10', class: "form-control" %>
              <%= f.submit "送信", class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto mt-3">
      <h1>welcome to <span class="fas fa-book"></span><strong>Bookers</strong>!!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 mt-3">
      <h1>
        Welcom to <span class="fas fa-book"></span><strong>Bookers</strong>!!
      </h1>
      <p>In<span class="fas fa-book"></span><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class="button-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3" href="<%= new_user_session_path %>" role="button">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block" href="<%= new_user_registration_path %>" role="button">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/484d7c7efd.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-light">
      <nav class="navbar navbar-expand-lg navbar-light custom-hamburger">
        <div class="container">
          <a href="<%= destroy_user_session_path %>" data-method="delete" class="navbar-brand text-light">Bookers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <a href="<%= user_path(current_user.id) %>" class="nav-link text-light"><span class="fas fa-home"></span> Home</a>
              <a href="<%= users_path %>" class="nav-link text-light"><span class="fas fa-users"></span> Users</a>
              <a href="<%= books_path %>" class="nav-link text-light"><span class="fas fa-book-open"></span> Books</a>
              <a href="<%= destroy_user_session_path %>" data-method="delete" class="nav-link text-light"><span class="fas fa-sign-out-alt"></span>logout</a>
            <% else %>
              <a href="<%= root_path %>" class="nav-link text-light"><span class="fas fa-home"></span> Home</a>
              <a href="<%= home_about_path %>" class="nav-link text-light"><span class="fas fa-link"></span> About</a>
              <a href="<%= new_user_registration_path %>" class="nav-link text-light"><span class="fas fa-user-plus"></span>sign up</a>
              <a href="<%= new_user_session_path %>" class="nav-link text-light"><span class="fas fa-sign-in-alt"></span>login</a>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
    <%= yield %>
  <footer>
    <div class="containermt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/templates/_template.html.erb
<!--UserInfoのテンプレ -->
<h2>User Info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table">
  <tbody>
    <tr>
      <td>Name</td>
      <td><strong><%= user.name %></strong></td>
    </tr>
    <tr>
      <td>Introduction</td>
      <td><strong><%= user.introduction %></strong></td>
    </tr>
  </tbody>
</table>

<!-- user編集ボタン -->
<div class="row">
  <a class="btn btn-outline-secondary btn-block" href="<%= edit_user_path(user.id) %>" role="button"><span class="fas fa-user-cog"></span></a>
</div>

<!-- createBookのテンプレ -->
<h2 class="mt-3">New book</h2>
<%= form_with model: book, url: books_path, method: :post do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, class: "form-label" %>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
      <h2>User info</h2>
      <%= form_with model: @user, method: :patch do |f| %>

        <div class="form-group">
          <label class="form-label">Name</label>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">Image</label>
          <%= f.file_field :profile_image, accept: "image/*",class:"form-control-file" %>
        </div>
        <div class="form-group">
          <label class="form-label">IntroductionI</label>
          <!--Userの自己紹介を入れる-->
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="actions">
          <!-- updateボタン -->
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: 'templates/template', locals: { book: @newBook , user: @currentUser} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <!-- Usersテーブル -->
      <h2>Users</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <!--Userを取り出す-->
          <% @users.each do |user| %>
            <tr>
              <td>
              <% if user.profile_image.attached? %>
                <%= image_tag user.profile_image, size: "80x80" %>
              <% else %>
                <%= image_tag 'no_image', size: "80x80" %>
              <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--フラッシュメッセージ作成しろ-->
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "templates/template", locals: {book: @new_book, user: @user} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <!-- テーブル -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th> </th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @userBooks.each do |book| %>
            <tr>
              <td>
                <!--User プロフィール画像-->
                <%= link_to user_path(book.user_id) do %>
                  <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <!--titleを本の詳細画面にする -->
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                <span class="fa-solid fa-heart"></span><%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                <span class="fa-regular fa-heart"></span><%= book.favorites.count %>
                <% end %>
              <% end %>
              <td>コメント数:<%= book.book_comments.count %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>